---
- name: 'Check dependencies'
  python_requirements_facts:
    dependencies:
      - 'openstack'
  register: 'openstack_deps'
  delegate_to: "{{ hostvars[item]['openstack_api_host'] }}"
  loop: "{{ query('inventory_hostnames', '{{ ansible_play_hosts }}' ) }}"

- name: 'Install dependencies'
  include_tasks: 'openstack_install.yml'
  loop: "{{ openstack_deps['results'] }}"
  when:
    - true # remove me!
    - item.not_found | length != 0

- name: "Load {{ target_action }} variables"
  include_vars: "openstack_{{ target_action }}.yml"

- name: 'Check for complete input, skip is OK'
  fail:
    msg: 'Missing input, please check documentation'
  when: target_state is not defined

- name: 'Check if state is allowed, skip is OK'
  fail:
    msg: 'Invalid/unsuppored state!'
  when: target_state not in supported_states

- name: 'Check required config dirs'
  file:
    state: 'directory'
    path: "{{ ansible_env.HOME }}/{{ config_dir }}"
  loop:
    - '.config/openstack'
    - '.ssh'
  loop_control:
    loop_var: 'config_dir'

- name: 'Check OpenstackSDK config file'
  template:
    src: 'clouds.yml.j2'
    dest: "{{ ansible_env.HOME }}/.config/openstack/clouds.yml"
    mode: 0440

- name: 'Create RSA SSH keypair'
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_openstack_rsa"
    type: 'rsa'
    size: 4096

- name: 'Register keypair in Openstack'
  os_keypair:
    cloud: 'openstack'
    state: 'present'
    name: 'ansible_rsa'
    public_key_file: "{{ ansible_env.HOME }}/.ssh/id_openstack_rsa.pub"

- name: "Run {{ target_action }} playbook"
  include_tasks: "openstack_{{ target_action }}.yml"
