---
- name: 'Execute server action'
  os_server_action:
    cloud: "{{ openstack_auth_cloud_name }}"
    region_name: "{{ openstack_region }}"
    state: "{{ target_state }}"
    server: "{{ target_args.name }}"
  when: target_state != 'rebuild'

- name: 'Rebuild server from image'
  os_server_action:
    cloud: "{{ openstack_auth_cloud_name }}"
    region_name: "{{ openstack_region }}"
    state: "{{ target_state }}"
    server: "{{ target_args.name }}"
    image: "{{ target_args.image }}"
  when: target_state == 'rebuild'
