---
- name: 'Gather API host facts'
  setup:
    gather_subset:
      - 'min'
  register: 'api_facts'

- name: 'Include OS specific vars'
  include_vars: "{{ ansible_os_family }}.yml"
  no_log: true

- name: 'Install dependencies'
  package:
    name:
      - "{{ openssh_client_pkg }}"

- name: 'Install dependencies from PiP'
  pip:
    name: "{{ openstacksdk_pkg }}"
    state: 'present'
