---
- name: 'Include OS specific vars'
  include_vars: "{{ ansible_os_family }}.yml"
  no_log: true

- name: 'Install dependencies'
  package:
    name:
      - 'openssh-client'

- name: 'Install dependencies from PiP'
  pip:
    name: "{{ openstacksdk_pkg }}"
    state: 'present'
