---
- name: 'Ensure network'
  os_subnets_facts:
    cloud: "{{ openstack_auth_cloud_name }}"
    region_name: "{{ openstack_region }}"
  register: 'subnet_list'

- set_fact:
    subnets:
      - '{{ subnets + [ subnet.name ] }}'
  loop: '{{ openstack_subnets }}'
  loop_control:
    loop_var: 'subnet'
  when: '"subnet" in subnet.name'

- debug:
    msg: '{{ subnets }}'
