---
- name: 'Ensure router'
  os_router:
    cloud: "{{ openstack_auth_cloud_name }}"
    name: "rtr-{{ target_args.name }}"
    state: "{{ target_state }}"
    interfaces: "{{ target_args.interfaces | default([]) }}"
    region_name: "{{ openstack_region }}"
