---
- name: 'Create inventory'
  hosts: 'all'
  tasks:
    - name: 'Add new host'
      add_host:
        name: "{{ ansible_facts['hostname'] }}"
        group: 'openstack_api'
        openstack_api_host: "{{ ansible_facts['hostname'] }}"
        openstack_api_validate: true
        openstack_api_url: 'https://identity.openstack.cloudvps.com/v3'
        openstack_api_user: 'ansible@usn.nl'
        openstack_api_pass: 'CEccvfT5Rq9CdPA_'
        openstack_project_name: 'BUN000054 Playground'
        openstack_project_id: '798f47152791498893b8c61d3d240cf2'
        openstack_region: 'AMS'
      changed_when: false

- name: 'Cleanup'
  hosts: 'openstack_api'
  tasks:
    - name: 'Remove rtr-mgmt'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'router'
        target_state: 'absent'
        target_args:
          name: 'mgmt'

    - name: 'Remove srv-vpnbe'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'server_persistent'
        target_state: 'absent'
        target_args:
          name: 'srv-vpnbe'

    - name: 'Remove srv-vpnfe'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'server_persistent'
        target_state: 'absent'
        target_args:
          name: 'srv-vpnfe'

    - name: 'Remove srv-proxy'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'server_persistent'
        target_state: 'absent'
        target_args:
          name: 'srv-proxy'

    - name: 'Remove secgrp-ext-shell'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'security_group'
        target_state: 'absent'
        target_args:
          name: 'ext-shell'

    - name: 'Remove secgrp-ext-openvpn'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'security_group'
        target_state: 'absent'
        target_args:
          name: 'ext-openvpn'

    - name: 'Remove secgrp-mgmt-shell'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'security_group'
        target_state: 'absent'
        target_args:
          name: 'mgmt-shell'

    - name: 'Remove net-mgmt'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'network'
        target_state: 'absent'
        target_args:
          name: 'mgmt'

    - name: 'Remove net-vpnfe'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'network'
        target_state: 'absent'
        target_args:
          name: 'vpnfe'

    - name: 'Remove net-proxy'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'network'
        target_state: 'absent'
        target_args:
          name: 'proxy'
