---
- name: 'Create inventory'
  hosts: 'all'
  tasks:
    - name: 'Add new host'
      add_host:
        name: "{{ ansible_facts['hostname'] }}"
        group: 'openstack_api'
        openstack_api_host: "{{ ansible_facts['hostname'] }}"
        openstack_api_validate: true
        openstack_api_url: 'https://identity.openstack.cloudvps.com/v3'
        openstack_api_user: 'ansible@usn.nl'
        openstack_api_pass: 'CEccvfT5Rq9CdPA_'
        openstack_project_name: 'BUN000054 Playground'
        openstack_project_id: '798f47152791498893b8c61d3d240cf2'
        openstack_region: 'AMS'
        openstack_ssh_key_name: 'molecule_managed_key'
      changed_when: false

- name: 'Converge'
  hosts: 'openstack_api'
  tasks:
    - name: 'Create rtr-mgmt'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'router'
        target_state: 'present'
        target_args:
          name: 'mgmt'
          interfaces:
            - 'subnet-vpnfe'
            - 'subnet-vpnbe'

    - name: 'Remove interface from rtr-mgmt'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        target_action: 'router'
        target_state: 'add_interface'
        target_args:
          name: 'mgmt'
          interfaces:
            - 'subnet-mgmt'
