---
# Add credential type to Ansible Tower/AWX for use with this role:
#
# 1. Add the following variable to the host_vars for localhost (use ansible-vault to protect secrets!):
#     - tower_hostname
#     - tower_username
#     - tower_password
# 2. Run this playbook
- name: 'Install credential type'
  hosts: 'localhost'
  tasks:
    - name: 'Create credential type'
      tower_credential_type:
        name: 'Openstack SSH key'
        description: 'SSH public key to attach to newly provisioned Compute instances'
        kind: 'cloud'
        inputs:
          fields:
            - type: 'string'
              id: 'key_name'
              label: 'SSH key name'
            - type: 'string'
              id: 'public_key'
              label: 'SSH public key'
              multiline: true
          required:
            - 'key_name'
            - 'public_key'
        injectors:
          extra_vars:
            openstack_ssh_key_name: 'key_name'
            openstack_ssh_public_key: 'public_key'
        state: 'present'
        tower_host: "{{ tower_hostname }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: 'false'
